services:
  pythonenv:
    container_name: ${PROJECT_NAME}-pythonenv
    build:
      context: ..
      dockerfile: docker/pythonenv/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
        WORKDIR: ${PROJECT_DIR}
        USER_ID: ${HOST_UID}
        GROUP_ID: ${HOST_GID}
        BASE_IMAGE: ${BASE_IMAGE}
        PYTHON_VERSION: ${PYTHON_VERSION}
        UV_VERSION: ${UV_VERSION}
    env_file:
      .env
    ports:
      - ${NOTEBOOK_PORT}:8000
    volumes:
      - ${PROJECT_DIR}:${PROJECT_DIR}

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"